export const KEY_GET_ADMIN_USER = 'KEY_GET_ADMIN_USER'
export const REGISTER_ADMIN_USER = 'REGISTER_ADMIN_USER'

export const KEY_GET_SCHOOL_GRADES = 'KEY_GET_SCHOOL_GRADES'
export const KEY_GET_SCHOOL_GRADE = 'KEY_GET_SCHOOL_GRADE'
export const KEY_CREATE_SCHOOL_GRADE = 'KEY_CREATE_SCHOOL_GRADE'
export const KEY_UPDATE_SCHOOL_GRADE = 'KEY_UPDATE_SCHOOL_GRADE'
export const KEY_DELETE_SCHOOL_GRADE = 'KEY_DELETE_SCHOOL_GRADE'

export const KEY_GET_TEACHERS = 'KEY_GET_TEACHERS'
export const KEY_GET_TEACHER = 'KEY_GET_TEACHER'
export const KEY_CREATE_TEACHER = 'KEY_CREATE_TEACHER'
export const KEY_UPDATE_TEACHER = 'KEY_UPDATE_TEACHER'
export const KEY_DELETE_TEACHER = 'KEY_DELETE_TEACHER'
